=== OmkarKirpan/java-course/src/net/azib/java/students/t030629/homework/io/decathlonResults.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="competitors" type="competitorsType"/>

    <xs:complexType name="competitorsType">
        <xs:sequence>
            <xs:element name="athlete" type="orderedAthleteType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="orderedAthleteType">
        <xs:sequence>
            <xs:element name="place" type="xs:positiveInteger"/>
            <xs:element name="personal_data" type="personal_dataType"/>
            <xs:element name="results" type="resultsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="personal_dataType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="birth" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="dateType">
        <xs:restriction base="xs:date">
            <xs:pattern value="dd.MM.YYYY"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="resultsType">
        <xs:sequence>
            <xs:element name="result" minOccurs="10" maxOccurs="10">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="event" type="xs:string"/>
                            <xs:attribute name="unit" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="total_score" type="xs:positiveInteger"/>
    </xs:complexType>

</xs:schema>

=== OmkarKirpan/java-course/test/net/azib/java/students/t030629/homework/io/decathlonResults.xml
<?xml version="1.0" encoding="UTF-8"?>
<competitors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="decathlonResults.xsd">
    <athlete>
        <place>1</place>
        <personal_data>
            <name>Siim Susi</name>
            <birth>1.01.1976</birth>
            <country>Estonia</country>
        </personal_data>
        <results total_score="4234">
            <result event="100 m sprint" unit="sec">12.61</result>
            <result event="Long jump" unit="m">5.00</result>
            <result event="Shot put" unit="m">9.22</result>
            <result event="High jump" unit="m">1.50</result>
            <result event="400 m sprint" unit="min:sec">59.39</result>
            <result event="110 m hurdles" unit="sec">16.43</result>
            <result event="Discus throw" unit="m">21.60</result>
            <result event="Pole vault" unit="m">2.60</result>
            <result event="Javelin throw" unit="m">35.81</result>
            <result event="1500 m race" unit="min:sec">5:25.72</result>
        </results>
    </athlete>    
    <athlete>
        <place>2</place>
        <personal_data>
            <name>Василий Пупкин</name>
            <birth>21.10.1980</birth>
            <country>Ukraine</country>
        </personal_data>
        <results total_score="3100">
            <result event="100 m sprint" unit="sec">13.43</result>
            <result event="Long jump" unit="m">4.35</result>
            <result event="Shot put" unit="m">8.64</result>
            <result event="High jump" unit="m">1.50</result>
            <result event="400 m sprint" unit="min:sec">1:06.06</result>
            <result event="110 m hurdles" unit="sec">19.05</result>
            <result event="Discus throw" unit="m">24.89</result>
            <result event="Pole vault" unit="m">2.20</result>
            <result event="Javelin throw" unit="m">33.48</result>
            <result event="1500 m race" unit="min:sec">6:51.01</result>
        </results>
    </athlete>
</competitors>
