=== OmkarKirpan/java-course/src/net/azib/java/students/t040719/homework/xml/DecathlonResults.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xs:element name="decathlon" type="decathlonType" />
	
	<xs:complexType name="decathlonType">
		<xs:sequence>
			<xs:element name="athlete" type="athleteType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="athleteType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="birthday" type="dateType"/>
			<xs:element name="country" type="countryType"/>
			<xs:element name="score" type="scoreType" />
			<xs:element name="place" type="placeType"/>
			<xs:element name="event" type="eventType" minOccurs="10" maxOccurs="10" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="scoreType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="15000"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="placeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]+(-[0-9]+)?" />
		</xs:restriction>
		
	</xs:simpleType>
	
	<xs:complexType name="eventType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="result" type="xs:string"/>
			<xs:element name="unit" type="unitType"/>
		</xs:sequence>
		<xs:attribute name="order" type="orderType" />
	</xs:complexType>
	
	<xs:complexType name="countryType">
		<xs:sequence>
			<xs:element name="code" type="countryCodeType"/>
			<xs:element name="name" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="countryCodeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{2}" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="orderType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="10"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="unitType">
		<xs:restriction base="xs:string">
	    	<xs:enumeration value="m"/>
	    	<xs:enumeration value="sec"/>
	    	<xs:enumeration value="min:sec"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="dateType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-3][0-9][.][0-1][0-9][.][1-2][09][0-9][0-9]" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== OmkarKirpan/java-course/test/net/azib/java/students/t040719/homework/io/test.xml
<?xml version="1.0" encoding="UTF-8"?>

<decathlon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://rmg.planet.ee/DecathlonResults.xsd">
  <athlete>
    <name>Siim Susi</name>
    <birthday>01.01.1999</birthday>
    <country>
      <code>EE</code>
      <name>ESTONIA</name>
    </country>
    <score>4234</score>
    <place>1</place>
    <event order="1">
      <name>100 m sprint</name>
      <result>12.61</result>
      <unit>sec</unit>
    </event>
    <event order="2">
      <name>Long jump</name>
      <result>5.00</result>
      <unit>m</unit>
    </event>
    <event order="3">
      <name>Shot put</name>
      <result>9.22</result>
      <unit>m</unit>
    </event>
    <event order="4">
      <name>High jump</name>
      <result>1.50</result>
      <unit>m</unit>
    </event>
    <event order="5">
      <name>400 m sprint</name>
      <result>59.39</result>
      <unit>min:sec</unit>
    </event>
    <event order="6">
      <name>110 m hurdles</name>
      <result>16.43</result>
      <unit>sec</unit>
    </event>
    <event order="7">
      <name>Discus throw</name>
      <result>21.60</result>
      <unit>m</unit>
    </event>
    <event order="8">
      <name>Pole vault</name>
      <result>2.60</result>
      <unit>m</unit>
    </event>
    <event order="9">
      <name>Javelin throw</name>
      <result>35.81</result>
      <unit>m</unit>
    </event>
    <event order="10">
      <name>1500 m race</name>
      <result>5:25.72</result>
      <unit>min:sec</unit>
    </event>
  </athlete>
</decathlon>
