=== OmkarKirpan/java-course/src/net/azib/java/students/t073862/homework/output.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="scores">
	<xs:complexType>
    <xs:sequence>
		<xs:element name="score" maxOccurs="unbounded">
			<xs:complexType>
    		<xs:sequence>
    			<xs:element name="place" type="xs:id"/>
        		<xs:element name="name" type="xs:string"/>
            	<xs:element name="dob" type="xs:string"/>
            	<xs:element name="iso" type="xs:integer"/>
            	<xs:element name="points" type="xs:integer"/>
            	<xs:element name="scoreData" type="xs:string"/>
    		</xs:sequence>
		</xs:complexType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== OmkarKirpan/java-course/src/net/azib/java/students/t073862/homework/output.test.xml
<?xml version="1.0" encoding="UTF-8"?>
<scores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="output.xsd">
	
			<score>
				<place>1</place>
				<name>Peeter Tomberg</name>
				<dob>18.06.1988</dob>
				<iso>ee</iso>
				<points>9990</points>
				<scoreData>[10.395, 7.76, 18.4, 2.2, 46.17, 13.8, 56.17, 5.28, 77.19, 233.79]</scoreData>
			</score>
			
		
</scores>
