=== OmkarKirpan/java-course/src/net/azib/java/students/t092877/homework/decathlon.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="competition">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="40"/>
							<xs:whiteSpace value="collapse"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="location">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="40"/>
							<xs:whiteSpace value="collapse"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="date" type="xs:date"/>
				<xs:element name="athletes">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="athlete" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="40"/>
													<xs:whiteSpace value="collapse"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="date_of_birth" type="xs:date"/>
										<xs:element name="country_code">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="[A-Z]{2}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="score" type="xs:positiveInteger"/>
										<xs:element name="place">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="[1-9]+[0-9]*[-]?[1-9]?[1-9]*"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="results">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="event" minOccurs="10" maxOccurs="10">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="name">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:enumeration value="100m"/>
																			<xs:enumeration value="long jump"/>
																			<xs:enumeration value="shot put"/>
																			<xs:enumeration value="high jump"/>
																			<xs:enumeration value="400m"/>
																			<xs:enumeration value="110m hurdles"/>
																			<xs:enumeration value="discus throw"/>
																			<xs:enumeration value="pole vault"/>
																			<xs:enumeration value="javelin throw"/>
																			<xs:enumeration value="1500m"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="result">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="value">
																				<xs:simpleType>
																					<xs:restriction base="xs:decimal">
																						<xs:fractionDigits value="2"/>
																					</xs:restriction>
																				</xs:simpleType>
																			</xs:element>
																			<xs:element name="units">
																				<xs:simpleType>
																					<xs:restriction base="xs:string">
																						<xs:enumeration value="seconds"/>
																						<xs:enumeration value="meters"/>
																					</xs:restriction>
																				</xs:simpleType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name="type" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:enumeration value="running"/>
																		<xs:enumeration value="jumping"/>
																		<xs:enumeration value="throwing"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
											<xs:unique name="unique_event">
												<xs:selector xpath="event"/>
												<xs:field xpath="name"/>
											</xs:unique>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== OmkarKirpan/java-course/src/net/azib/java/students/t092877/homework/decathlon.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="decathlon.xsl"?>
<competition id="d10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="decathlon.xsd">
	<name>DECATHLON4BEER</name>
	<location>Tallinn</location>
	<date>2005-05-18</date>
	<athletes>
		<athlete>
			<name>Erki Nool</name>
			<date_of_birth>1972-05-19</date_of_birth>
			<country_code>CZ</country_code>
			<score>8610</score>
			<place>3</place>
			<results>
				<event type="running">
					<name>100m</name>
					<result>
						<value>10.62</value>
						<units>seconds</units>
					</result>
				</event>
				<event type="jumping">
					<name>long jump</name>
					<result>
						<value>8.07</value>
						<units>meters</units>
					</result>
				</event>
				<event type="throwing">
					<name>shot put</name>
					<result>
						<value>16.57</value>
						<units>meters</units>
					</result>
				</event>
				<event type="jumping">
					<name>high jump</name>
					<result>
						<value>2.00</value>
						<units>meters</units>
					</result>
				</event>
				<event type="running">
					<name>400m</name>
					<result>
						<value>47.74</value>
						<units>seconds</units>
					</result>
				</event>
				<event type="running">
					<name>110m hurdles</name>
					<result>
						<value>13.80</value>
						<units>seconds</units>
					</result>
				</event>
				<event type="throwing">
					<name>discus throw</name>
					<result>
						<value>45.51</value>
						<units>meters</units>
					</result>
				</event>
				<event type="jumping">
					<name>pole vault</name>
					<result>
						<value>5.00</value>
						<units>meters</units>
					</result>
				</event>
				<event type="throwing">
					<name>javelin throw</name>
					<result>
						<value>68.53</value>
						<units>meters</units>
					</result>
				</event>
				<event type="running">
					<name>1500m</name>
					<result>
						<value>235.13</value>
						<units>seconds</units>
					</result>
				</event>
			</results>
		</athlete>
		<athlete>
			<name>Tomáš DVORÁK</name>
			<date_of_birth>1972-05-19</date_of_birth>
			<country_code>CZ</country_code>
			<score>8902</score>
			<place>1</place>
			<results>
				<event type="running">
					<name>100m</name>
					<result>
						<value>10.62</value>
						<units>seconds</units>
					</result>
				</event>
				<event type="jumping">
					<name>long jump</name>
					<result>
						<value>8.07</value>
						<units>meters</units>
					</result>
				</event>
				<event type="throwing">
					<name>shot put</name>
					<result>
						<value>16.57</value>
						<units>meters</units>
					</result>
				</event>
				<event type="jumping">
					<name>high jump</name>
					<result>
						<value>2.00</value>
						<units>meters</units>
					</result>
				</event>
				<event type="running">
					<name>400m</name>
					<result>
						<value>47.74</value>
						<units>seconds</units>
					</result>
				</event>
				<event type="running">
					<name>110m hurdles</name>
					<result>
						<value>13.80</value>
						<units>seconds</units>
					</result>
				</event>
				<event type="throwing">
					<name>discus throw</name>
					<result>
						<value>45.51</value>
						<units>meters</units>
					</result>
				</event>
				<event type="jumping">
					<name>pole vault</name>
					<result>
						<value>5.00</value>
						<units>meters</units>
					</result>
				</event>
				<event type="throwing">
					<name>javelin throw</name>
					<result>
						<value>68.53</value>
						<units>meters</units>
					</result>
				</event>
				<event type="running">
					<name>1500m</name>
					<result>
						<value>235.13</value>
						<units>seconds</units>
					</result>
				</event>
			</results>
		</athlete>
		<athlete>
			<name>Dean Macey</name>
			<date_of_birth>1972-05-19</date_of_birth>
			<country_code>CZ</country_code>
			<score>8705</score>
			<place>2</place>
			<results>
				<event type="running">
					<name>100m</name>
					<result>
						<value>10.62</value>
						<units>seconds</units>
					</result>
				</event>
				<event type="jumping">
					<name>long jump</name>
					<result>
						<value>8.07</value>
						<units>meters</units>
					</result>
				</event>
				<event type="throwing">
					<name>shot put</name>
					<result>
						<value>16.57</value>
						<units>meters</units>
					</result>
				</event>
				<event type="jumping">
					<name>high jump</name>
					<result>
						<value>2.00</value>
						<units>meters</units>
					</result>
				</event>
				<event type="running">
					<name>400m</name>
					<result>
						<value>47.74</value>
						<units>seconds</units>
					</result>
				</event>
				<event type="running">
					<name>110m hurdles</name>
					<result>
						<value>13.80</value>
						<units>seconds</units>
					</result>
				</event>
				<event type="throwing">
					<name>discus throw</name>
					<result>
						<value>45.51</value>
						<units>meters</units>
					</result>
				</event>
				<event type="jumping">
					<name>pole vault</name>
					<result>
						<value>5.00</value>
						<units>meters</units>
					</result>
				</event>
				<event type="throwing">
					<name>javelin throw</name>
					<result>
						<value>68.53</value>
						<units>meters</units>
					</result>
				</event>
				<event type="running">
					<name>1500m</name>
					<result>
						<value>235.13</value>
						<units>seconds</units>
					</result>
				</event>
			</results>
		</athlete>
	</athletes>
</competition>
